"use strict";
let desiredplces = ["Madina", "Najaf", "Kazmain", "Karbala", "Mashhad"];
console.log(desiredplces);
let ddesiredplaces = [...desiredplces];
ddesiredplaces = ddesiredplaces.sort();
console.log(ddesiredplaces);
console.log(desiredplces);
ddesiredplaces = ddesiredplaces.reverse();
console.log(ddesiredplaces);
console.log(desiredplces);
ddesiredplaces = ddesiredplaces.reverse();
console.log(ddesiredplaces);
console.log(desiredplces);
